kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: flask
  namespace: fleet-local
spec:
  branch: main
  insecureSkipTLSVerify: false
  repo: https://github.com/joshyorko/fleet
  targetNamespace: flask
  paths:
  - flask
